# Generated by Django 4.2.20 on 2025-04-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('num_rounds', models.IntegerField()),
                ('num_devices', models.IntegerField()),
                ('noise_multiplier', models.FloatField()),
                ('accuracy', models.JSONField()),
                ('loss', models.JSONField()),
                ('leakage', models.JSONField()),
                ('latency', models.JSONField()),
                ('epsilon', models.JSONField()),
            ],
        ),
    ]
